{% set version = '0.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-testit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/testit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/testit/testit_{{ version }}.tar.gz
  sha256: 08a9c19c962eae60f4ab58885a23e0bc239efc39da682290be436c066f8d97f7

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rstudioapi
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('testit')"           # [not win]
    - "\"%R%\" -e \"library('testit')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/yihui/testit
  license: GPL
  summary: Provides two convenience functions assert() and test_pkg() to facilitate testing R
    packages.
  license_family: GPL

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: testit
# Type: Package
# Title: A Simple Package for Testing R Packages
# Version: 0.8
# Authors@R:  person("Yihui", "Xie", role = c("aut", "cre"), email = "xie@yihui.name", comment = c(ORCID = "0000-0003-0645-5666"))
# Description: Provides two convenience functions assert() and test_pkg() to facilitate testing R packages.
# License: GPL
# URL: https://github.com/yihui/testit
# BugReports: https://github.com/yihui/testit/issues
# Suggests: rstudioapi
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-06-14 03:31:26 UTC; yihui
# Author: Yihui Xie [aut, cre] (<https://orcid.org/0000-0003-0645-5666>)
# Maintainer: Yihui Xie <xie@yihui.name>
# Repository: CRAN
# Date/Publication: 2018-06-14 05:47:58 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
