travis:
  secure:
    BINSTAR_TOKEN: B5mMKrnCEObbct1385poovMnojtbTtqBQFJTQGHXn2Ux2QFnTYxp/nym6iYUJHLg34A32+mwaNLA91f7qUWZe09AJrbrwmyFhA1eu7nVGoKSYVx4RrhHNWwEiTim/UWGWfouNO0JZg4HdgZ0w5zguWLoRNcmDRlFnpuGiA2pJLa7vJ10qfHLBQj5mX6TAJZyUu8BRfdD8B03kfdBupa8LhD5QWDrNqrTJrX6D8uVpB33x9pJklUEkRV2S0otIpI3ohevm84YMWAjQMKxVzx55fPmqk8o5w59fpc8xmizO2ldilMP6VbG6JenvL3sw6N9DyboA+ElpYLVUip/PIG+LkhwyIreg7iwhbL9Jp6Ma7Z9h+76OEyTcr3Had+AJiv/Gu52uCjEPslmX0dM5Knp4FC2d8YPJ6gMysSoNvG4d8oQTpvI36QLacgXxAsGDYs624VJnY/w6m8M8ZNjgdojq+R5/zPxGswvM6h5unwazybl4BcKqIf/jdoDl0iXDm9h1x5MMwmrNGiyYS/61Alq+0Yt/EZv6hPd9kqy5VYQ/n1cZ5vx0Hj3D8mC6nrTh85TeKhZ/FDiWHwWuLW8Ta5BjAOb6MVmuCw/5hiLG+eQ7TZ+Dn/eBVQ2kXq/RuIz8kqpmTPmTKPnpnXIPaccjZdkzZczWPMyaGyW++RDOcrsjOA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
