travis:
  secure:
    BINSTAR_TOKEN: gmxK3MtnYsHw8TUik7hRNt9lWYW+AbbiM6FEvhikZH5kWGa6t7zQAA/MBBiUvzmK6PUICXN9RDk/NBczMwdSSrUCb0K5kTkW4IduxvshWtstVXKahoRRfw3q6jClAPrUzmiBoQMhay3Jk7NVLed2+5gRKf8RZ/u23L1bGcbmQpBtDIiNSj8JRHn9ZHzqGz/CG/Esh/qr/cAi5ef7gbixGqM9PMwLsRZScI6sjxtk3klCQU8VNK9qxqer0pJ33etFIz7iZsyK169x0wo0oGO9i+NaHQ5lVljLS40iMIans1QEq7UEjfoyu7ur+8veGNa6LK325NvxLA2S0UuMjMoad4k/Ex74pKpnH+L5/I1tsxatnTzeZ/6TW7Z62fkGPfcIMy3Sy94O+Px+pZ3rAbXLzUyZywDBSpnVvK3lVQrXqy5lzIR9SJWBDkhRl8LN3D4K5L+WSCxTwWU2GaVdnZGU6wMdCidQHJ5KHYjaSpq77tmk3hE6p66VVHHZYa/v9Ig+xfIlWiCf+AEDpRwPUO9qrGO6xg3eM1dg5YVVgJjaF4NLC/pmZdCo/6QJomG3hDI4XEAydj+wFsBLGhfLPsUU53ZThHxZobJdqtnRs0H4ZZ5sRdi89rR5aocafdl7NVyO1crPNtQVb3aa57aPwEP/dmN+afXpFBvpiANrLJxpbLY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
